version: "3.9"
services:

  server:
    build: ./api
    container_name: hngserverstage2-c
    ports:
      - 8000:8000

  frontend:
    container_name: hngfrontendstage2-c
    image: hngfrontendstage2-i
    build: 
      context: ./frontend
    
    ports:
      - 3000:80

    links:
      - server

